### ISSUE TITLE
What just happened? 

### ISSUE THREAD

**Issue by pgamerx** [PGamerX-Legacy/soon#11]
You now need an API key to access API!
It's a manual process and will take time for approval, but till that you can use **Demo Version**! 

Demo version is available at the same domain, all you need to do is add /demo/ before every endpoint
for example - https://api.pgamerx.com/joke/any will be changed to **https://api.pgamerx.com/demo/joke/any**

**YOU WILL ONLY GET 50 REQUESTS PER MINUTE IN DEMO VERSION, ONCE YOU GET AN API KEY FOR FREE, YOU WILL GET 100 requests per minute**

Endpoints - https://api.pgamerx.com/endpoints [UPDATED]
Register API key at https://api.pgamerx.com/register
Support server - https://pgamerx.com/discord
Donate - https://ko-fi.com/pgamerx

**Comment by CoblinFrog** [comment]
Is it really necessary for the email? Can I give you my discord tag instead for you to contact me?

**Comment by pgamerxdev** [comment]
> Is it really necessary for the email? Can I give you my discord tag instead for you to contact me?

it sure is so I can ban users from creating further keys if they break rules
Also API requests are closed for next 12 hours.
I am sorry

**Comment by CoblinFrog** [comment]
Do you have docs? How do I use this api key?

**Comment by pgamerxdev** [comment]
> Do you have docs? How do I use this api key?

Yes, Just check out [This Updated link](https://api.pgamerx.com/endpoints)
**You will also find python and javascript examples there**

**Comment by CoblinFrog** [comment]
Can you post a tutorial? I don't know where and how I can use this. This is really confusing. Could you maybe release another version but the old API?

**Comment by PGamerX** [comment]
> Can you post a tutorial? I don't know where and how I can use this. This is really confusing. Could you maybe release another version but the old API?

Uh, I don’t know if you even read the endpoints. 
everything is same the only new thing is api key 
I don’t know what you mean, nothing is changed 
Did you look at the examples?

**Comment by PGamerX** [comment]
> > Can you post a tutorial? I don't know where and how I can use this. This is really confusing. Could you maybe release another version but the old API?
> 
> Uh, I don’t know if you even read the endpoints.
> everything is same the only new thing is api key
> I don’t know what you mean, nothing is changed
> Did you look at the examples?

This is my alt account, also see these examples https://github.com/pgamerxdev/projects/tree/api/examples

**Comment by CoblinFrog** [comment]
Thanks! I couldn't find any examples on your website so I had some trouble using this.

**Comment by pgamerxdev** [comment]
> Thanks! I couldn't find any examples on your website so I had some trouble using this.

haha no problems 
btw here are the examples
![Screenshot 2021-04-12 at 9 39 33 AM](https://user-images.githubusercontent.com/71639879/114339494-00afd600-9b73-11eb-8a77-398a432d2513.png)

**Comment by CoblinFrog** [comment]
Also I get an error putting in the API key.
```
TypeError: __init__() got an unexpected keyword argument 'api_key'
```
Please help!

**Comment by pgamerxdev** [comment]
> Also I get an error putting in the API key.
> 
> ```
> TypeError: __init__() got an unexpected keyword argument 'api_key'
> ```
> 
> Please help!

Please update your prsaw package
Also, this package is made by @codewithswastik and @FalseDev

**Comment by FalseDev** [comment]
> Also I get an error putting in the API key.
> 
> ```
> TypeError: __init__() got an unexpected keyword argument 'api_key'
> ```
> 
> Please help!

Run this to update `prsaw`, make sure you're on version 0.3.1
```py
pip install prsaw -U
```

**Comment by NightZan999** [comment]
**UPDATE**
> 1) You can now buy special plans at https://api.pgamerx.com/premium which will give you a better API key with better features!
> 2) prsaw no-more works for v3 new libraries are in the works
> 3) You can now sign up with discord, **you will be added to the support server, if you leave your API key *will* be terminated**

**Comment by aarkay06** [comment]
@pgamerxdev You have any discord channel for question related to it?

**Comment by pgamerx** [comment]
> @pgamerxdev You have any discord channel for question related to it?

yes, visit #api_and_wrappers in [This server](https://u.pgamerx.com/discord)

**Comment by aarkay06** [comment]
Can you tell me what's the error..I have posted it in the Discord server --->JS Development channel @pgamerxdev
