### ISSUE TITLE
Status code being always 200.

### ISSUE THREAD

**Issue by nerdguyahmad** [PGamerX-Legacy/soon#18]
Status code is always 200 on API calls regardless of any kind of error like invalid API keys etc.

**Comment by pgamerxdev** [comment]
> Status code is always 200 on API calls regardless of any kind of error like invalid API keys etc.
I will work on that

**Comment by Hunter2807** [comment]
Yes, this is happening with me too...

**Comment by pgamerxdev** [comment]
It Looks like I won't be able to fix it since ExpressJS Doesn't provide that facility in the version I am using.
I will upgrade the version once my exams are finished i.e in about a week

**Comment by pgamerxdev** [comment]
This issue is fixed
You can leave suggestions here telling what should be codes other than 401 and 200

**Comment by nerdguyahmad** [comment]
Suggestion: 403 code for plan not authorised.

**Comment by nerdguyahmad** [comment]
# Brief description of what I think status codes on different events.

## **Success:** `200` 
Pretty self explanatory. Don't need any description I believe.


## **Invalid API key:** `401`
401 or "Unauthorised" can be used for invalid API keys. As it says itself, Unauthorised. Some people may have doubt on it being 403 instead. Read the next one.

## **Plan not available on API key:** `403`
403 or "Forbidden" can be used to indicate that user is forbidden from using an endpoint because they don't have valid permissions to access it.

## **Bad/Invalid parameters:** `400`
400 or "Bad request" can be used to indicate that user has supplied either invalid or unsupported type in parameters.

Not only the above status codes will help the users but also API wrapper developers to add different errors to warn the users.

**Comment by pgamerx** [comment]
I think this issue is fixed?

**Comment by izxxr** [comment]
> I think this issue is fixed? 

@pgamerxdev Weather endpoint returns 200 response on Invalid City error. It should return 404.

**Comment by pgamerx** [comment]
> > I think this issue is fixed? 
> 
> @pgamerxdev Weather endpoint returns 200 response on Invalid City error. It should return 404.

Ah sh*t
